Proyecto final/Solucion/ApiChat/MVCChat/Controllers/CrearUsuarioController.cs
using MVCChat.Models;
using MVCChat.Singleton;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVCChat.Controllers
{
    public class CrearUsuarioController : Controller
    {
        // GET: CrearUsuario
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(FormCollection collection) {
            var _User = new User();

            _User.Nombre = collection["Nombre"];
            _User.Apellido = collection["Apellido"];
            _User.Username = collection["Username"];
            _User.Contrasena = collection["Contrasena"];
            _User.Telefono = int.Parse(collection["Telefono"]);


            var Respuesta = Data.Instancia.RocketChat.Cliente.PostAsJsonAsync("Create", _User);
            Respuesta.Wait();
            var Result = Respuesta.Result;
            if (Result.StatusCode == HttpStatusCode.Created)
            {

                var ReadTask = Result.Content.ReadAsStringAsync();
                ReadTask.Wait();
                return RedirectToAction("Index", "Login");

            }
            return RedirectToAction("Crear");


        }
    }
}

Proyecto final/Solucion/ApiChat/MVCChat/Controllers/LoginController.cs
using MVCChat.Models;
using MVCChat.Singleton;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCChat.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            var user = new User();
            user.Username = collection["Username"];
            user.Contrasena = collection["Contrasena"];

            var value = Data.Instancia.RocketChat.Cliente.PostAsJsonAsync("authenticate", user);
            value.Wait();

            var Result = value.Result;

            if (Result.StatusCode == HttpStatusCode.Accepted)
            {
                var ReadTask = Result.Content.ReadAsStringAsync();
                ReadTask.Wait();
                var Jwt = JsonConvert.DeserializeObject<Jwt>(ReadTask.Result);
                Data.Instancia.RocketChat.Cliente.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", Jwt.Token);
                return RedirectToAction("HomePerfil", "Perfil");
            }
            return RedirectToAction("Index");
        }
    }
}

Proyecto final/Solucion/ApiChat/MVCChat/Views/Login/Index.cshtml
@model MVCChat.Models.User

@{ ViewBag.Title = "Login";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<br />
<br />
<br />

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />
                    <div class="row">
                        <div class="col-sm-3"></div>
                        <div class="col-md-6">
                            <div class="panel panel-default">
                                <div class="panel-heading" style="background-color:steelblue">
                                    <h2 class="panel-title"><strong>Login</strong></h2>
                                </div>
                                <div class="panel-body" style="background-color:coral">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Contrasena, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="pull-right col-lg-6">
                                            <input type="submit" value="Ingresar" class="btn btn-warning" style="background-color:black" />
                                        </div>
                                    </div>
                                    @Html.ActionLink("Registrarse", "Crear", "CrearUsuario")
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                </div>}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}